BoxLayout:
    orientation: "vertical"
    BoxLayout:
        Button:
            size_hint_x: 1
            text: "this is it"
            on_press: root.test()
        Button:
            size_hint_x: 2
        Button:
            size_hint_x: 1
    BoxLayout:
        Button:
            size_hint_x: 1
        Button:
            size_hint_x: 2
        Button:
            size_hint_x: 3
    BoxLayout:
        TextInput
    ListView:
        item_strings: ["foo", "bar"]

